from __future__ import annotations

import ast
import hashlib
import json
import re
from dataclasses import asdict, dataclass
from pathlib import Path


GENERATED_PATTERNS = (
    "generated by",
    "auto-generated",
    "autogenerated",
    "do not edit",
    "codegen",
    "@generated",
)

BOILERPLATE_PATTERNS = (
    "copyright",
    "licensed under",
    "all rights reserved",
    "generated code",
)

DOC_HINTS = ("readme", "docs", "doc", "tutorial", "guide", "example")
TEST_HINTS = ("test", "tests", "spec", "specs", "__tests__", "fixture")


@dataclass(slots=True)
class FileQualityReport:
    path: str
    source_type: str
    quality_score: float
    accepted: bool
    rejection_reason: str | None
    normalized_hash: str
    is_valid_python: bool | None
    is_generated: bool
    is_minified: bool
    is_boilerplate: bool
    line_count: int
    non_empty_line_count: int
    avg_line_length: float
    max_line_length: int
    size_bytes: int

    def to_dict(self) -> dict[str, object]:
        return asdict(self)


def normalize_code(text: str) -> str:
    normalized_lines = [" ".join(line.strip().split()) for line in text.splitlines() if line.strip()]
    return "\n".join(normalized_lines)


def hash_normalized_code(text: str) -> str:
    normalized = normalize_code(text)
    return hashlib.sha256(normalized.encode("utf-8")).hexdigest()


def infer_source_type(path: str | Path, text: str) -> str:
    lowered_path = str(path).lower()
    if any(hint in lowered_path for hint in TEST_HINTS):
        return "test"
    if any(hint in lowered_path for hint in DOC_HINTS):
        return "doc"

    stripped = text.lstrip()
    if stripped.startswith('"""') or stripped.startswith("'''") or stripped.startswith("/**"):
        return "doc"
    if re.search(r"(?m)^\s*(describe|it|test)\s*\(", text):
        return "test"
    return "implementation"


def assess_file_quality(path: Path, text: str, config: dict) -> FileQualityReport:
    lines = text.splitlines()
    non_empty_lines = [line for line in lines if line.strip()]
    line_count = len(lines)
    non_empty_count = len(non_empty_lines)
    max_line_length = max((len(line) for line in lines), default=0)
    avg_line_length = (sum(len(line) for line in lines) / max(line_count, 1)) if lines else 0.0
    size_bytes = len(text.encode("utf-8"))
    lowered = text.lower()

    is_generated = any(pattern in lowered for pattern in GENERATED_PATTERNS)
    is_boilerplate = any(pattern in lowered for pattern in BOILERPLATE_PATTERNS)
    is_minified = _looks_minified(
        text=text,
        avg_line_length=avg_line_length,
        max_line_length=max_line_length,
        line_count=line_count,
    )
    is_valid_python = _validate_python(path, text, config)
    source_type = infer_source_type(path, text)
    normalized_hash = hash_normalized_code(text)

    rejection_reason: str | None = None
    if size_bytes > int(config.get("max_file_size_bytes", 200_000)):
        rejection_reason = "file_too_large"
    elif line_count > int(config.get("max_code_lines", 2_000)):
        rejection_reason = "too_many_lines"
    elif max_line_length > int(config.get("max_line_length", 400)):
        rejection_reason = "line_too_long"
    elif config.get("filter_generated_code", True) and is_generated:
        rejection_reason = "generated_code"
    elif config.get("filter_minified_code", True) and is_minified:
        rejection_reason = "minified_code"
    elif config.get("filter_boilerplate", True) and is_boilerplate and non_empty_count < 12:
        rejection_reason = "boilerplate"
    elif config.get("validate_python", True) and path.suffix.lower() == ".py" and is_valid_python is False:
        rejection_reason = "python_syntax_error"

    quality_score = _estimate_quality_score(
        text=text,
        source_type=source_type,
        is_generated=is_generated,
        is_minified=is_minified,
        is_boilerplate=is_boilerplate,
        line_count=line_count,
        non_empty_count=non_empty_count,
    )

    return FileQualityReport(
        path=str(path),
        source_type=source_type,
        quality_score=quality_score,
        accepted=rejection_reason is None,
        rejection_reason=rejection_reason,
        normalized_hash=normalized_hash,
        is_valid_python=is_valid_python,
        is_generated=is_generated,
        is_minified=is_minified,
        is_boilerplate=is_boilerplate,
        line_count=line_count,
        non_empty_line_count=non_empty_count,
        avg_line_length=avg_line_length,
        max_line_length=max_line_length,
        size_bytes=size_bytes,
    )


def build_chunk_quality_metadata(
    *,
    chunk_text: str,
    source_report: FileQualityReport,
) -> dict[str, object]:
    normalized_hash = hash_normalized_code(chunk_text)
    lines = chunk_text.splitlines()
    quality_score = _estimate_quality_score(
        text=chunk_text,
        source_type=source_report.source_type,
        is_generated=source_report.is_generated,
        is_minified=False,
        is_boilerplate=False,
        line_count=len(lines),
        non_empty_count=sum(1 for line in lines if line.strip()),
    )
    return {
        "normalized_hash": normalized_hash,
        "quality_score": quality_score,
        "line_count": len(lines),
        "non_empty_line_count": sum(1 for line in lines if line.strip()),
        "is_valid_target": source_report.is_valid_python if chunk_text and Path(source_report.path).suffix == ".py" else None,
    }


def export_quality_reports(path: Path, reports: list[FileQualityReport]) -> None:
    payload = [report.to_dict() for report in reports]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def _validate_python(path: Path, text: str, config: dict) -> bool | None:
    if not config.get("validate_python", True):
        return None
    if path.suffix.lower() != ".py":
        return None
    try:
        ast.parse(text)
    except SyntaxError:
        return False
    return True


def _looks_minified(
    *,
    text: str,
    avg_line_length: float,
    max_line_length: int,
    line_count: int,
) -> bool:
    if not text.strip():
        return False
    if line_count <= 3 and avg_line_length > 300:
        return True
    if max_line_length > 800:
        return True
    long_lines = sum(1 for line in text.splitlines() if len(line) > 400)
    if long_lines >= 3 and long_lines >= max(1, line_count // 4):
        return True
    return False


def _estimate_quality_score(
    *,
    text: str,
    source_type: str,
    is_generated: bool,
    is_minified: bool,
    is_boilerplate: bool,
    line_count: int,
    non_empty_count: int,
) -> float:
    score = 0.45
    if non_empty_count >= 6:
        score += 0.2
    if line_count >= 12:
        score += 0.15
    if source_type in {"test", "doc"}:
        score += 0.05
    if re.search(r"(?m)^\s*(def|class|function|export function|if|for|while|return)\b", text):
        score += 0.1
    if is_generated:
        score -= 0.35
    if is_minified:
        score -= 0.25
    if is_boilerplate:
        score -= 0.15
    return max(0.0, min(1.0, score))
